// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/sample.proto

package jmeshtru.protobuf;

public interface SampleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jmeshtru.protobuf.Sample)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
